version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:813048754227:task-definition/payment-service-task:6"
        LoadBalancerInfo:
          ContainerName: "payment-service-container"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"